althaus/C#/PlantShop/Models/Plant.cs
using System.ComponentModel.DataAnnotations;

namespace PlantShop.Models;

public class Plant()
{
    public int Plant_Id { get; set; }

    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "Make sure that the Name is at least 2 characters. Must start with a capital letter.")]
    [Required]
    [StringLength(255, MinimumLength = 2)]
    public string Name { get; set; }


    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "Make sure that the Name is at least 2 characters. Must start with a capital letter.")]
    [Required]
    [StringLength(255, MinimumLength = 2)]
    public string Family { get; set; }

    [RegularExpression("^(?:indoor(?!.*indoor)|outdoor(?!.*outdoor))$", ErrorMessage = "Plant can only be 'indoor or outdoor'")]
    [Required]
    public string IndoorOutdoor { get; set; }

    public string Plant_Image { get; set; }

    [RegularExpression(@"^[0-9]*$", ErrorMessage = "A quantity number is required. Use only whole numbers.")]
    [Required]
    public int Quantity { get; set; }
}

althaus/C#/PlantShop/Controllers/PlantController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PlantShop.Models;

namespace PlantShop.Controllers;

public class PlantController : Controller
{
    private readonly ILogger<StaffController> _logger;
    private readonly IConfiguration _configuration;

    public PlantController(ILogger<StaffController> logger, IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
    }

    public IActionResult Index()
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        return View(Database.Instance.GetAllPlant());
    }

    public IActionResult IndoorOnly()
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        return View(Database.Instance.IndoorOnlyPlant());
    }

    public IActionResult OutdoorOnly()
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        return View(Database.Instance.outdoorOnlyPlant());
    }

    public ActionResult Create(Plant plant)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));

        return View(plant);
    }

    public ActionResult CreateResult(Plant plant)
    {
        Database.Instance.AddPlant(plant);
        if (plant.Plant_Image == null)
        {
            plant.Plant_Image = DisplayNullImage();
        }
        return View(plant);
    }

    public ViewResult Display(int id)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        Plant idPlant = Database.Instance.GetAllPlant().FirstOrDefault(plant => plant.Plant_Id == id);
        return View(idPlant);
    }

    public ViewResult Edit(int id)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        Plant editPlant = Database.Instance.GetAllPlant().FirstOrDefault(plant => plant.Plant_Id == id);
        return View(editPlant);
    }

    public ViewResult EditResult(Plant plant)
    {
        Database.Instance.EditPlant(plant);
        if (plant.Plant_Image == null)
        {
            plant.Plant_Image = DisplayNullImage();
        }
        return View(plant);
    }

    public ViewResult Delete(int id, Plant plant)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        Plant deletePlant = Database.Instance.GetAllPlant().FirstOrDefault(plant => plant.Plant_Id == id);

        return View(deletePlant);
    }

    public ActionResult DeleteResult(Plant plant)
    {
        Database.Instance.DeletePlant(plant);
        return View(plant);
    }

    public String DisplayNullImage()
    {
        string NullImage = "Images/NullFlowerImage.png";
        return NullImage;
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

althaus/C#/PlantShop/Views/Plant/Create.cshtml
@model Plant;

<!-- This view's title -->
@{
    ViewData["Title"] = "Add Plants";
}

<!-- This view's heading -->
<h2>Add a plant to the system</h2>
<hr />

<!-- Adding a plant form -->
<div class="row">
    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <form asp-action="CreateResult">
            <!-- Hides Id feild for the Plant_ID as it autoincrements -->
            <input type="hidden" asp-for="Plant_Id" />
            <!-- Name input -->
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label">Name:</label>
                <input name="Name" asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <!-- Family input -->
            <div class="form-group">
                <label asp-for="@Model.Family" class="control-label">Family:</label>
                <input name="Family" asp-for="@Model.Family" class="form-control" />
                <span asp-validation-for="@Model.Family" class="text-danger"></span>
            </div>
            <!-- Indoor or Outdoor input -->
            <div class="form-group">
                <label asp-for="@Model.IndoorOutdoor" class="control-label">Indoor or Outdoor:</label>
                <input name="IndoorOutdoor" asp-for="@Model.IndoorOutdoor" class="form-control" />
                <span asp-validation-for="@Model.IndoorOutdoor" class="text-danger"></span>
            </div>
            <!-- Quantity input -->
            <div data-mdb-input-init class="form-outline" style="width: 22rem;">
                <label asp-for="@Model.Quantity" class="form-label">Quantity:</label>
                <input name="Quantity" asp-for="@Model.Quantity" class="form-control" type="number" required />
            </div>
            <!-- image input -->
            <div class="form-group">
                <label asp-for="@Model.Plant_Image" class="control-label">Plant Image:</label>
                <input name="PlantImage" asp-for="@Model.Plant_Image" class="form-control" />
            </div>
            <hr />
            <!-- Submit and cancel button -->
            <div class="form-group">
                <input type="submit" value="Add plant" class="btn btn-primary" />
                <a asp-controller="plant" asp-action="Index" class="btn btn-primary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

althaus/C#/PlantShop/Views/Plant/CreateResult.cshtml
@model Plant;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Newly Created Plant";
}

<!-- View heading -->
<h2>You have added the plant @Model.Name to the list</h2>

<!-- Results from add form input -->
<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>Name: </span>@Model.Name</p>
            <p class="fexi_header_para"><span>Family: </span> @Model.Family </p>
            <p class="fexi_header_para"><span>Indoor or Outdoor: </span> @Model.IndoorOutdoor </p>
            <p class="fexi_header_para"><span>Image: </span> @Model.Plant_Image</p>
            <p class="fexi_header_para"><span>Quantity: </span> @Model.Quantity</p>
        </div>
    </dl>
</div>
<!-- Back button to index view -->
<hr />
<div>
    <a asp-controller="Plant" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Plant/Delete.cshtml
@model Plant;
<!-- Title for view -->
@{
    ViewData["Title"] = "Delete Plant";
}
<!-- Heading for this view -->
<h2>Remove @Model.Name from the system</h2>

<!-- Alert to show what is being deleted -->
<div>
    <hr />
    <div class="alert alert-danger">
        Are you sure you want to delete?
    </div>
    <dl class="container">
        <div class="col-md-6 agile_tv_series_grid_right">
            <p class="fexi_header"><span>Plant ID: </span>@Model.Plant_Id</p>
            <p class="fexi_header"><span>Name: </span>@Model.Name</p>
            <p class="fexi_header_para"><span>Family: </span> @Model.Family </p>
            <p class="fexi_header_para"><span>Indoor or Outdoor: </span> @Model.IndoorOutdoor </p>
            <p class="fexi_header_para"><span>Image: </span> @Model.Plant_Image</p>
            <p class="fexi_header_para"><span>Quantity: </span> @Model.Quantity</p>
        </div>
    </dl>
</div>
<!-- Delete form -->
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteResult">
            <hr />
            <!-- Alert to ask for deletion input -->
            <div class="alert alert-danger">
                Retype the plants name and family to confirm.
            </div>
            <div>
                <!-- delete confirmation inputs -->
                <div class="form-group">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Family" class="control-label"></label>
                    <input asp-for="@Model.Family" class="form-control" />
                    <span asp-validation-for="@Model.Family" class="text-danger"></span>
                </div>
                <hr />
                <!-- Submit and cancel button -->
                <div>
                    <input asp-action="DeleteResult" type="submit" value="Delete" class="btn btn-primary" />
                    <a asp-controller="plant" asp-action="Index" class="btn btn-primary">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

althaus/C#/PlantShop/Views/Plant/DeleteResult.cshtml
@model Plant;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Deleted Plant";
}

<!-- View heading -->
<h2>Plant deleted successfully!</h2>

<!-- Results from add form input -->
<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>You have deleted plant from the system.</span></p>
        </div>
    </dl>
</div>
<!-- Back button to index view -->
<hr />
<div>
    <a asp-controller="Plant" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Plant/Display.cshtml
@model Plant;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Plant Page";
}
<!-- View heading -->
<h2>@Model.Name's Details</h2>

<!-- Singular plant details page -->
<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>Plant ID: </span>@Model.Plant_Id</p>
            <p class="fexi_header"><span>Name: </span>@Model.Name</p>
            <p class="fexi_header_para"><span>Family: </span> @Model.Family </p>
            <p class="fexi_header_para"><span>Indoor or Outdoor: </span> @Model.IndoorOutdoor </p>
            <p class="fexi_header_para"><span>Quantity: </span> @Model.Quantity</p>
            <p><span>Image: </span><img src="@Model.Plant_Image" class="plantimg-display" alt="Responsive image"></p>
        </div>
    </dl>
</div>
<!-- Back button to index view -->
<hr />
<div>
    <a asp-controller="Plant" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Plant/Edit.cshtml
@model Plant;
<!-- This view's title -->
@{
    ViewData["Title"] = "Edit Plant";
}

<!-- This view's heading -->
<h2>@Model.Name's Details</h2>
<hr />
<!-- Editing a plant form -->
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditResult">
            <!-- Hides Id feild for the Plant_ID as it autoincrements -->
            <input type="hidden" asp-for="@Model.Plant_Id" />
            <!-- Name input -->
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <!-- Family input -->
            <div class="form-group">
                <label asp-for="@Model.Family" class="control-label"></label>
                <input asp-for="@Model.Family" class="form-control" />
                <span asp-validation-for="@Model.Family" class="text-danger"></span>
            </div>
            <!-- Indoor or Outdoor input -->
            <div class="form-group">
                <label asp-for="@Model.IndoorOutdoor" class="control-label">Indoor or Outdoor</label>
                <input asp-for="@Model.IndoorOutdoor" class="form-control" />
                <span asp-validation-for="@Model.IndoorOutdoor" class="text-danger"></span>
            </div>
            <!-- Quantity input -->
            <div data-mdb-input-init class="form-outline" style="width: 22rem;">
                <label asp-for="@Model.Quantity" class="form-label">Quantity:</label>
                <input name="Quantity" asp-for="@Model.Quantity" class="form-control" type="number" required />
            </div>
            <!-- image input -->
            <div class="form-group">
                <label asp-for="@Model.Plant_Image" class="control-label">Plant Image:</label>
                <input name="Plant_Image" asp-for="@Model.Plant_Image" class="form-control" />
            </div>
            <hr />
            <!-- Submit and cancel button -->
            <div>
                <input asp-action="EditResult" type="submit" value="Save" class="btn btn-primary" />
                <a asp-controller="Plant" asp-action="Index" class="btn btn-primary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

althaus/C#/PlantShop/Views/Plant/EditResult.cshtml
@model Plant;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Changed Details";
}

<!-- View heading -->
<h2>Details changed successfully!</h2>

<!-- Results from add form input -->
<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>You have changed the details for the plant:</span></p>
            <p class="fexi_header"><span>Name: </span>@Model.Name</p>
            <p class="fexi_header_para"><span>Family: </span> @Model.Family </p>
            <p class="fexi_header_para"><span>Indoor or Outdoor: </span> @Model.IndoorOutdoor </p>
            <p class="fexi_header_para"><span>Image: </span> @Model.Plant_Image</p>
            <p class="fexi_header_para"><span>Quantity: </span> @Model.Quantity</p>
        </div>
    </dl>
</div>
<!-- Back button to index view -->
<hr />
<div>
    <a asp-controller="Plant" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Plant/Index.cshtml
@model List<Plant>;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Plant List";
}
<h1>Plant List</h1>
<hr />

<!-- Add new plants button -->
<div class="btn-group-top">
    <a asp-controller="Plant" asp-action="Create" class="btn btn-primary float-end">
        Add New Plants
    </a>
</div>
<!-- Database list table -->
<div class="page-container">
    <div class="table-responsive">
        <div class="scrollable">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Plant Id</th>
                        <th>Plant Image</th>
                        <th>Name</th>
                        <th>Family</th>
                        <th>Indoor or Outdoor</th>
                        <th>Quantity</th>
                        <th style="width: 1px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Plant plants in Model)
                    {
                        <tr>
                            <td>
                                @plants.Plant_Id
                            </td>
                            <td>
                                <img src="@plants.Plant_Image" alt="plantImagePreview" class="img-thumbnail">
                            </td>
                            <td>
                                @plants.Name
                            </td>
                            <td>
                                @plants.Family
                            </td>
                            <td>
                                @plants.IndoorOutdoor
                            </td>
                            <td>
                                @plants.Quantity
                            </td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown"
                                        aria-expanded="false" id="btnToggleActions">
                                        More Options
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="btnToggleActions">
                                        <li><a asp-controller="Plant" asp-action="Display" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Display</a></li>
                                        <li><a asp-controller="Plant" asp-action="Edit" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Edit</a></li>
                                        <li><a asp-controller="Plant" asp-action="Delete" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Delete</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Links for other options -->
<div class="btn-group-btm">
    <div class="btn-group" role="group">
        <a asp-controller="Plant" asp-action="Index" class="btn btn-default">Show All</a>
        <a asp-controller="Plant" asp-action="IndoorOnly" class="btn btn-default">Indoor Only</a>
        <a asp-controller="Plant" asp-action="OutdoorOnly" class="btn btn-default">Outdoor Only</a>
    </div>
</div>

althaus/C#/PlantShop/Views/Plant/IndoorOnly.cshtml
@model List<Plant>;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Indoor Plant List";
}
<h1>Plant List</h1>
<hr />

<!-- Add new plants button -->
<div class="btn-group-top">
    <a asp-controller="Plant" asp-action="Create" class="btn btn-primary float-end">
        Add New Plants
    </a>
</div>

<!-- Database list table -->
<div class="page-container">
    <div class="table-responsive">
        <div class="scrollable">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Plant Id</th>
                        <th>Plant Image</th>
                        <th>Name</th>
                        <th>Family</th>
                        <th>Indoor or Outdoor</th>
                        <th>Quantity</th>
                        <th style="width: 1px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Plant plants in Model)
                    {
                        <tr>
                            <td>
                                @plants.Plant_Id
                            </td>
                            <td>
                                <img src="@plants.Plant_Image" alt="plantImagePreview" class="img-thumbnail">
                            </td>
                            <td>
                                @plants.Name
                            </td>
                            <td>
                                @plants.Family
                            </td>
                            <td>
                                @plants.IndoorOutdoor
                            </td>
                            <td>
                                @plants.Quantity
                            </td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown"
                                        aria-expanded="false" id="btnToggleActions">
                                        More Options
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="btnToggleActions">
                                        <li><a asp-controller="Plant" asp-action="Display" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Display</a></li>
                                        <li><a asp-controller="Plant" asp-action="Edit" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Edit</a></li>
                                        <li><a asp-controller="Plant" asp-action="Delete" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Delete</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Links for other options -->
<div class="btn-group-btm">
    <div class="btn-group" role="group">
        <a asp-controller="Plant" asp-action="Index" class="btn btn-default">Show All</a>
        <a asp-controller="Plant" asp-action="IndoorOnly" class="btn btn-default">Indoor Only</a>
        <a asp-controller="Plant" asp-action="OutdoorOnly" class="btn btn-default">Outdoor Only</a>
    </div>
</div>

althaus/C#/PlantShop/Views/Plant/OutdoorOnly.cshtml
@model List<Plant>;

<!-- Title for this view -->
@{
    ViewData["Title"] = "Outdoor Plant List";
}
<h1>Plant List</h1>
<hr />

<!-- Add new plants button -->
<div class="btn-group-top">
    <a asp-controller="Plant" asp-action="Create" class="btn btn-primary float-end">
        Add New Plants
    </a>
</div>

<!-- Database list table -->
<div class="page-container">
    <div class="table-responsive">
        <div class="scrollable">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Plant Id</th>
                        <th>Plant Image</th>
                        <th>Name</th>
                        <th>Family</th>
                        <th>Indoor or Outdoor</th>
                        <th>Quantity</th>
                        <th style="width: 1px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Plant plants in Model)
                    {
                        <tr>
                            <td>
                                @plants.Plant_Id
                            </td>
                            <td>
                                <img src="@plants.Plant_Image" alt="plantImagePreview" class="img-thumbnail">
                            </td>
                            <td>
                                @plants.Name
                            </td>
                            <td>
                                @plants.Family
                            </td>
                            <td>
                                @plants.IndoorOutdoor
                            </td>
                            <td>
                                @plants.Quantity
                            </td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown"
                                        aria-expanded="false" id="btnToggleActions">
                                        More Options
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="btnToggleActions">
                                        <li><a asp-controller="Plant" asp-action="Display" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Display</a></li>
                                        <li><a asp-controller="Plant" asp-action="Edit" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Edit</a></li>
                                        <li><a asp-controller="Plant" asp-action="Delete" asp-route-id="@plants.Plant_Id"
                                                class="dropdown-item">Delete</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Links for other options -->
<div class="btn-group-btm">
    <div class="btn-group" role="group">
        <a asp-controller="Plant" asp-action="Index" class="btn btn-default">Show All</a>
        <a asp-controller="Plant" asp-action="IndoorOnly" class="btn btn-default">Indoor Only</a>
        <a asp-controller="Plant" asp-action="OutdoorOnly" class="btn btn-default">Outdoor Only</a>
    </div>
</div>