althaus/C#/PlantShop/Models/Staff.cs
using System.ComponentModel.DataAnnotations;
namespace PlantShop.Models;

public class Staff()
{
    public int Staff_Id { get; set; }

    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "Make sure that the Forename is at least 2 characters. Must start with a capital letter.")]
    [Required]
    [StringLength(255, MinimumLength = 2)]
    public string Forename { get; set; }

    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "Make sure that the Surname is at least 2 characters. Must start with a capital letter.")]
    [Required]
    [StringLength(255, MinimumLength = 2)]
    public string Surname { get; set; }

    //Restore when add entry works
    //public DateOnly DateOfBirth { get; set; }

    [RegularExpression("^[a-z]+(@greenplant.com)$", ErrorMessage = "Make sure the email is according to the company standard format *yourname@greenplant.com*. The email cannot have a capital letter in it.")]
    [Required]
    [StringLength(50, MinimumLength = 10)]
    public string Email { get; set; }

    [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$", ErrorMessage = "Paasword must have these conditions: Has minimum 8 characters in length.At least one uppercase English letter. At least one lowercase English letter. At least one digit.")]
    [Required]
    [StringLength(50, MinimumLength = 8)]
    public string Password { get; set; }

    [RegularExpression("^(?:manager(?!.*manager)|standard(?!.*standard))$", ErrorMessage = "Role can only be 'standard or manager'")]
    [Required]
    public string Role { get; set; }
}

althaus/C#/PlantShop/Controllers/StaffController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Security;
using PlantShop.Models;

namespace PlantShop.Controllers;

public class StaffController : Controller
{
    private readonly ILogger<StaffController> _logger;
    private readonly IConfiguration _configuration;

    public StaffController(ILogger<StaffController> logger, IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
    }

    public IActionResult Index()
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        return View(Database.Instance.GetAllStaff());
    }

    public ActionResult Create(Staff staff)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        return View(staff);
    }

    public ActionResult CreateResult(Staff staff)
    {
        //staff.Password = "password";
        Database.Instance.AddStaff(staff);
        return View(staff);
    }

    public ViewResult Display(int id)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        Staff idStaff = Database.Instance.GetAllStaff().FirstOrDefault(staff => staff.Staff_Id == id);
        return View(idStaff);
    }

    public ViewResult Edit(int id)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        Staff editStaff = Database.Instance.GetAllStaff().FirstOrDefault(staff => staff.Staff_Id == id);
        return View(editStaff);
    }

    public ViewResult EditResult(Staff staff)
    {
        Database.Instance.EditStaff(staff);
        staff.Email = staff.Forename + staff.Surname + "@greenplant.com";
        return View(staff);
    }

    public ViewResult Delete(int id, Staff staff)
    {
        Database.Instance.SetConnectionString(_configuration.GetValue<string>("ConnectionString"));
        Staff deleteStaff = Database.Instance.GetAllStaff().FirstOrDefault(staff => staff.Staff_Id == id);

        return View(deleteStaff);
    }

    public ActionResult DeleteResult(Staff staff)
    {
        Database.Instance.DeleteStaff(staff);
        return View(staff);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

althaus/C#/PlantShop/Views/Staff/Create.cshtml
@model Staff;
<!-- This view's title -->
@{
    ViewData["Title"] = "Register Staff";
}
<!-- This view's heading -->
<h2>Add staff to the system</h2>
<hr />
<!-- Adding new staff form -->
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateResult">
            <!-- Hides Id feild for the Staff_Id as it autoincrements -->
            <input type="hidden" asp-for="Staff_Id" />
            <!-- Forename input -->
            <div class="form-group">
                <label asp-for="@Model.Forename" class="control-label">Forename:</label>
                <input name="Forename" asp-for="@Model.Forename" class="form-control" />
                <span asp-validation-for="@Model.Forename" class="text-danger"></span>
            </div>
            <!-- Surname input -->
            <div class="form-group">
                <label asp-for="@Model.Surname" class="control-label">Surname:</label>
                <input name="Surname" asp-for="@Model.Surname" class="form-control" />
                <span asp-validation-for="@Model.Surname" class="text-danger"></span>
            </div>
            <!-- Email input -->
            <div class="form-group">
                <label asp-for="@Model.Email" class="control-label">Staff Email:</label>
                <input name="Email" value="YourName@greenplant.com" asp-for="@Model.Email" class="form-control" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
                <small id="emailHelp" class="form-text text-muted">Please type in email according to the company
                    standard email format. *YourName@greenplant.com*</small>
            </div>
            <!-- Password input -->
            <div class="form-group">
                <label asp-for="@Model.Password" class="control-label">Password:</label>
                <input name="Password" value="Password1" asp-for="@Model.Password" class="form-control" readonly />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div> <small id="emailHelp" class="form-text text-muted">All newly registered staff get a default password
                and must change it immediately!</small>
            <!-- Role input -->
            <div class="form-group">
                <label asp-for="@Model.Role" class="control-label">Role:</label>
                <input name="Role" asp-for="@Model.Role" class="form-control" />
                <span asp-validation-for="@Model.Role" class="text-danger"></span>
            </div>
            <hr />
            <!-- Submit and cancel button -->
            <div class="form-group">
                <input type="submit" value="Register Staff" class="btn btn-primary" />
                <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Cancel</a>
            </div>
        </form>
    </div>
</div>

althaus/C#/PlantShop/Views/Staff/CreateResult.cshtml
@model Staff;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Staff Page";
}
<!-- View heading -->
<h2>You have registered @Model.Forename @Model.Surname's details onto the system</h2>
<hr />
<!-- Results from add form input -->
<div>
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>Name: </span>@Model.Forename @Model.Surname</p>
            <p class="fexi_header_para"><span>@Html.DisplayNameFor(Model => Model.Email): </span> @Model.Email </p>
            <p class="fexi_header_para"><span>Password: </span> @Model.Password </p>
            <p class="fexi_header_para"><span>Role: </span> @Model.Role </p>
        </div>
    </dl>
</div>
<!-- Back button to index view -->
<hr />
<div>
    <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Staff/Delete.cshtml
@model Staff;
<!-- This view's title -->
@{
    ViewData["Title"] = "Delete Staff";
}
<!-- This view's heading -->
<h2>Remove @Model.Forename @Model.Surname from the system</h2>

<!-- Alert to show what is being deleted -->
<div>
    <hr />
    <div class="alert alert-danger">
        Are you sure you want to delete?
    </div>
    <dl class="container">
        <div class="col-md-6 agile_tv_series_grid_right">
            <p class="fexi_header"><span>Name: </span>@Model.Forename @Model.Surname</p>
            <p class="fexi_header_para"><span>@Html.DisplayNameFor(Model => Model.Email): </span> @Model.Email </p>
        </div>
    </dl>
</div>
<hr />
<!-- Delete form -->
<div class="row">
    <div class="col-md-4">
        <!-- Alert to ask for deletion input -->
        <div class="alert alert-danger">
            Retype the forename and surname to confirm.
        </div>
        <form asp-action="DeleteResult">
            <!-- delete confirmation inputs -->
            <div class="form-group">
                <div>
                    <label asp-for="@Model.Forename" class="control-label"></label>
                    <input asp-for="@Model.Forename" class="form-control" />
                    <span asp-validation-for="@Model.Forename" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Surname" class="control-label"></label>
                    <input asp-for="@Model.Surname" class="form-control" />
                    <span asp-validation-for="@Model.Surname" class="text-danger"></span>
                </div>
                <hr />
                <!-- Submit and cancel button -->
                <div>
                    <input type="submit" value="Delete" class="btn btn-primary" />
                    <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

althaus/C#/PlantShop/Views/Staff/DeleteResult.cshtml
@model Staff;

@{
    ViewData["Title"] = "Deleted Staff";
}

<h2>Staff deleted successfully!</h2>

<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>You have deleted staff from the system.</span></p>
        </div>
    </dl>
</div>

<hr />
<div>
    <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Staff/Display.cshtml
@model Staff;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Staff Page";
}
<!-- View heading -->
<h2>@Model.Forename @Model.Surname's Details</h2>

<!-- Singular plant details page -->
<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>Staff ID: </span>@Model.Staff_Id</p>
            <p class="fexi_header"><span>Name: </span>@Model.Forename @Model.Surname</p>
            <p class="fexi_header_para"><span>@Html.DisplayNameFor(Model => Model.Email): </span> @Model.Email </p>
            <p class="fexi_header"><span>Role: </span>@Model.Role</p>
        </div>
    </dl>
</div>
<!-- Back button to index view -->
<hr />
<div>
    <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Staff/Edit.cshtml
@model Staff;
<!-- This view's title -->
@{
    ViewData["Title"] = "Edit Staff";
}
<!-- This view's heading -->
<h2>@Model.Forename @Model.Surname's Details</h2>
<hr />
<!-- Editing staff details form -->
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditResult">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Staff_Id" />
            <div class="form-group">
                <label asp-for="@Model.Forename" class="control-label"></label>
                <input asp-for="@Model.Forename" class="form-control" />
                <span asp-validation-for="@Model.Forename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Surname" class="control-label"></label>
                <input asp-for="@Model.Surname" class="form-control" />
                <span asp-validation-for="@Model.Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="control-label"></label>
                <input asp-for="@Model.Email" class="form-control" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Password" class="control-label"></label>
                <input asp-for="@Model.Password" class="form-control" />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Role" class="control-label">Role:</label>
                <input name="Role" asp-for="@Model.Role" class="form-control" />
                <span asp-validation-for="@Model.Role" class="text-danger"></span>
            </div>
            <hr />
            <div>
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

althaus/C#/PlantShop/Views/Staff/EditResult.cshtml
@model Staff;

@{
    ViewData["Title"] = "Changed Details";
}

<h2>Details changed successfully!</h2>

<div>
    <hr />
    <dl class="container">
        <div class="col-md-3 agile_grid_right">
            <p class="fexi_header"><span>You have changed the staff details to:</span></p>
            <p class="fexi_header"><span>Name: </span>@Model.Forename @Model.Surname</p>
            <p class="fexi_header_para"><span>Email: </span> @Model.Email </p>
            <p class="fexi_header_para"><span>Password: </span> @Model.Password </p>
            <p class="fexi_header_para"><span>Role: </span> @Model.Role </p>
        </div>
    </dl>
</div>

<hr />
<div>
    <a asp-controller="Staff" asp-action="Index" class="btn btn-primary">Back</a>
</div>

althaus/C#/PlantShop/Views/Staff/Index.cshtml
@model List<Staff>;
<!-- Title for this view -->
@{
    ViewData["Title"] = "Staff List";
}
<h1>Staff List</h1>
<hr />
<!-- Add new staff button -->
<div class="btn-group-top">
    <a asp-controller="Staff" asp-action="Create" class="btn btn-primary float-end">
        Register New Staff
    </a>
</div>
<!-- Database list table -->
<div class="page-container">
    <div class="table-responsive">
        <div class="scrollable">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Staff Id</th>
                        <th>Forename</th>
                        <th>Surname</th>
                        <th>Email</th>
                        <th>Password</th>
                        <th>Role</th>
                        <th style="width: 1px;">Modify</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Staff staff in Model)
                    {
                        <tr>
                            <td>
                                @staff.Staff_Id
                            </td>
                            <td>
                                @staff.Forename
                            </td>
                            <td>
                                @staff.Surname
                            </td>
                            <td>
                                @staff.Email
                            </td>
                            <td>
                                @staff.Password
                            </td>
                            <td>
                                @staff.Role
                            </td>
                            <td>
                                <div class="dropdown">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown"
                                        aria-expanded="false" id="btnToggleActions">
                                        More Options
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="btnToggleActions">
                                        <li><a asp-controller="Staff" asp-action="Display" asp-route-id="@staff.Staff_Id"
                                                class="dropdown-item">Display</a></li>
                                        <li><a asp-controller="Staff" asp-action="Edit" asp-route-id="@staff.Staff_Id"
                                                class="dropdown-item">Edit</a></li>
                                        <li><a asp-controller="Staff" asp-action="Delete" asp-route-id="@staff.Staff_Id"
                                                class="dropdown-item">Delete</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>